name: Build Multi-Platform

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y dpkg-dev wget

    - name: Build Linux executable
      run: |
        pyinstaller --onefile --windowed --name=u2be_down --icon=assets/icon.png --add-data="assets:assets" gui.py

    - name: Create .deb package
      run: |
        chmod +x create_deb.sh
        ./create_deb.sh

    - name: Create AppImage
      run: |
        chmod +x create_appimage.sh
        ./create_appimage.sh

    - name: Upload Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: u2be_down-linux-executable
        path: dist/u2be_down

    - name: Upload .deb package
      uses: actions/upload-artifact@v4
      with:
        name: u2be_down-linux-deb
        path: "*.deb"

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: u2be_down-linux-appimage
        path: "*.AppImage"

  build-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --name=u2be_down --icon=assets/icon.ico --add-data="assets;assets" gui.py

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: u2be_down-windows
        path: dist/u2be_down.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build macOS executable and app
      run: |
        chmod +x build_macos.sh
        ./build_macos.sh

    - name: Upload macOS app
      uses: actions/upload-artifact@v4
      with:
        name: u2be_down-macos-app
        path: dist/U2Be Down.app

    - name: Upload macOS DMG
      uses: actions/upload-artifact@v4
      with:
        name: u2be_down-macos-dmg
        path: dist/U2Be-Down-macOS.dmg
      if: always()

  create-release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
    - name: Download Linux executable
      uses: actions/download-artifact@v4
      with:
        name: u2be_down-linux-executable
        path: ./linux/

    - name: Download Linux .deb
      uses: actions/download-artifact@v4
      with:
        name: u2be_down-linux-deb
        path: ./linux/

    - name: Download Linux AppImage
      uses: actions/download-artifact@v4
      with:
        name: u2be_down-linux-appimage
        path: ./linux/

    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: u2be_down-windows
        path: ./windows/

    - name: List files (debug)
      run: |
        echo "=== Linux files ==="
        ls -la ./linux/
        echo "=== Windows files ==="
        ls -la ./windows/

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          linux/u2be_down
          linux/*.deb
          linux/*.AppImage
          windows/u2be_down.exe
        body: |
          ## 🎉 U2Be Down - Release ${{ github.ref_name }}

          ### 📥 Downloads Linux:
          - **🐧 Executável**: `u2be_down` (standalone)
          - **📦 Pacote .deb**: Para Debian/Ubuntu (`sudo dpkg -i u2be-down_*.deb`)
          - **🚀 AppImage**: Universal Linux (execute diretamente)

          ### 📥 Downloads Windows:
          - **🪟 Executável**: `u2be_down.exe` (standalone)

          ### 🚀 Como usar:

          **Linux (.deb):**
          ```bash
          sudo dpkg -i u2be-down_*.deb
          sudo apt-get install -f  # Se necessário
          u2be_down
          ```

          **Linux (AppImage):**
          ```bash
          chmod +x U2Be_Down-*.AppImage
          ./U2Be_Down-*.AppImage
          ```

          **Linux/Windows (Executável):**
          ```bash
          chmod +x u2be_down  # Linux apenas
          ./u2be_down  # ou u2be_down.exe no Windows
          ```

          ### 📋 Funcionalidades:
          - ✅ Download de vídeos do YouTube
          - ✅ Conversão automática para MP3
          - ✅ Interface gráfica moderna
          - ✅ Player de música integrado
          - ✅ Suporte a playlists
          - ✅ Downloads paralelos
          - ✅ Histórico de downloads

          ### ⚙️ Requisitos:
          - **FFmpeg** instalado no sistema
          - **Linux**: `sudo apt install ffmpeg`
          - **Windows**: Baixar de https://ffmpeg.org

          ### 🐛 Problemas?
          Reporte em: https://github.com/fchevitarese/u2be_down/issues
        tag_name: ${{ github.ref_name }}
        name: "U2Be Down v${{ github.ref_name }}"
        draft: false
        prerelease: false