name: Build Multi-Platform

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build Linux executable
      run: |
        pyinstaller --onefile --console --name=u2be_down main.py

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: u2be_down-linux
        path: dist/u2be_down

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build Windows executable
      run: |
        pyinstaller --onefile --console --name=u2be_down main.py

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: u2be_down-windows
        path: dist/u2be_down.exe

  create-release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download Linux artifact
      uses: actions/download-artifact@v3
      with:
        name: u2be_down-linux
        path: ./linux/

    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: u2be_down-windows
        path: ./windows/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          linux/u2be_down
          windows/u2be_down.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
